---
core:
  username: mafiabot
  password: mafiapassword
  owner: ownerAccount
plugins:
  './src/mafiabot':
    thread: 52778
    mods:
     - mod
    players:
     - player1
     - player2
    db: './mafiadb'
    name: testMafia
    voteBars: bastard