---
core:
  username: username
  password: password
  owner: accalia
  ignoreUsers:
    - blakeyrat
    - PaulaBean
  ignoreCategories:
    - 8
    - 23
  cooldownPeriod: 0
plugins:
  './plugins/mafiabot'
    thread: 52778
    mods:
     - mod
    players:
     - player1
     - player2
    db: './mafiadb'
